import { v4 as uuidv4 } from "uuid";

const listaItens = [
  {
    categoria: "processador",
    fabricante: "intel",
    id: uuidv4(),
    img: "/images/intel1.jpg",
    garantia: "36 meses",
    name: "Processador Intel Core i3-10105, Cache 6MB, 3.7GHz (4.4GHz Max Turbo), LGA 1200 - BX8070110105",
    pathName:
      "processador-intel-core-i3-10105-cache-6mb-3-7ghz-4-4ghz-max-turbo-lga-1200-bx8070110105",
    pPrazo: 1000,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "intel",
    id: uuidv4(),
    img: "/images/intel2.jpg",
    garantia: "36 meses",
    name: "Processador Intel Core i5-12400F, Cache 18MB, 2.5GHz (4.4GHz Max Turbo), LGA 1700 - BX8071512400F",
    pathName:
      "processador-intel-core-i5-12400f-cache-18mb-2-5ghz-4-4ghz-max-turbo-lga-1700-bx8071512400f",
    pPrazo: 1600,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "intel",
    id: uuidv4(),
    img: "/images/intel3.jpg",
    garantia: "36 meses",
    name: "Processador Intel Core i7-12700K, Cache 25MB, 3.6GHz (5.0GHz Max Turbo), LGA 1700 - BX8071512700K",
    pathName:
      "processador-intel-core-i7-12700k-cache-25mb-3-6ghz-5-0ghz-max-turbo-lga-1700-bx8071512700k",
    pPrazo: 3400,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "intel",
    id: uuidv4(),
    img: "/images/intel4.jpg",
    garantia: "36 meses",
    name: "Processador Intel Core i9-12900K, Cache 30MB, 3.2GHz (5.2GHz Max Turbo), LGA 1700 - BX8071512900K",
    pathName:
      "processador-intel-core-i9-12900k-cache-30mb-3-2ghz-5-2ghz-max-turbo-lga-1700-bx8071512900k",
    pPrazo: 7500,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "amd",
    id: uuidv4(),
    img: "/images/amd1.jpg",
    garantia: "12 meses",
    name: "Processador AMD Ryzen 3 3200G, 3.6GHz (4.0GHz Max Turbo), AM4, Vídeo Integrado, 4 Núcleos  - YD3200C5FHBOX",
    pathName:
      "processador-amd-ryzen-3-3200g-3-6ghz-4-0ghz-max-turbo-am4-vídeo-integrado-4-núcleos--yd3200c5fhbox",
    pPrazo: 1100,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "amd",
    id: uuidv4(),
    img: "/images/amd2.jpg",
    garantia: "12 meses",
    name: "Processador AMD Ryzen 5 5600G, 3.9GHz (4.4GHz Max Turbo), AM4, Vídeo Integrado, 6 Núcleos - 100-100000252BOX",
    pathName:
      "processador-amd-ryzen-5-5600g-3-9ghz-4-4ghz-max-turbo-am4-vídeo-integrado-6-núcleos-100100000252box",
    pPrazo: 1900,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "amd",
    id: uuidv4(),
    img: "/images/amd3.jpg",
    garantia: "12 meses",
    name: "Processador AMD Ryzen 7 5700G, 3.8GHz (4.6GHz Max Turbo), AM4, Vídeo Integrado, 8 Núcleos - 100-100000263BOX",
    pathName:
      "processador-amd-ryzen-7-5700g-3-8ghz-4-6ghz-max-turbo-am4-vídeo-integrado-8-núcleos-100100000263box",
    pPrazo: 2400,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "processador",
    fabricante: "amd",
    id: uuidv4(),
    img: "/images/amd4.jpg",
    garantia: "12 meses",
    name: "Processador AMD Ryzen 9 5900X, 3.7GHz (4.8GHz Max Turbo), AM4, Vídeo Integrado, 12 Núcleos - 100-100000061WOF",
    pathName:
      "processador-amd-ryzen-9-5900x-3-7ghz-4-8ghz-max-turbo-am4-vídeo-integrado-12-núcleos-100100000061wof",
    pPrazo: 3600,
    tags: [],
    destaque: false,
    promo: false,
    specs: [
      "Número de núcleos: 4",
      "Nº de threads: 8",
      "Frequência baseada em processador: 3.70 GHz",
      "Frequência turbo max: 4.40 GHz",
      "Cache: 6 MB Intel Smart Cache",
      "TDP: 65 W",
      "Tamanho máximo de memória: 128 GB",
      " Tipos de memória: DDR4-2666",
      "Nº máximo de canais de memória: 2",
      "Gráficos UHD Intel: 630",
      "Resolução máxima (HDMI 1.4): 4096 x 2160@30Hz",
      "Resolução máxima (DP): 4096 x 2304@60Hz",
      "Nº de monitores aceitos: 3",
      "Soquetes suportados: FCLGA1200",
    ],
  },
  {
    categoria: "fonte",
    fabricante: "gigabyte",
    id: uuidv4(),
    img: "/images/fonte-gigabyte-p450b.jpg",
    garantia: "36 meses",
    name: "Fonte Gigabyte GP-P450B 450W, 80 Plus Bronze - 28200-P450B-1BRR",
    pathName: "fonte-gigabyte-gpp450b-450w-80-plus-bronze-28200p450b1brr",
    pPrazo: 375,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Marca: Gigabyte",
      "Modelo: 28200-P450B-1BRR",
      "PFC: PFC ativo (> 0,9 típico)",
      "Tensão de entrada: 100-240 Vac (gama completa)",
      "Corrente de entrada: 8-4 A",
      "Frequência de entrada: 60-50 Hz",
      "Capacidade de saída: 450W",
      "80 PLUS: Bronze",
      "Eficiência: 85% em carga típica",
      "Dimensões: 150 x 140 x 86 mm",
      "Peso: 1912 gramas (bruto com embalagem)",
    ],
  },
  {
    categoria: "fonte",
    fabricante: "xpg",
    id: uuidv4(),
    img: "/images/fonte-xpg-850.jpg",
    garantia: "36 meses",
    name: "Fonte XPG Core Reactor, 850W, 80 Plus Gold Modular",
    pathName: "fonte-xpg-core-reactor-850w-80-plus-gold-modular",
    pPrazo: 940,
    tags: [],
    destaque: false,
    promo: false,
    specs: [
      "Marca: Gigabyte",
      "Modelo: 28200-P450B-1BRR",
      "PFC: PFC ativo (> 0,9 típico)",
      "Tensão de entrada: 100-240 Vac (gama completa)",
      "Corrente de entrada: 8-4 A",
      "Frequência de entrada: 60-50 Hz",
      "Capacidade de saída: 450W",
      "80 PLUS: Bronze",
      "Eficiência: 85% em carga típica",
      "Dimensões: 150 x 140 x 86 mm",
      "Peso: 1912 gramas (bruto com embalagem)",
    ],
  },
  {
    categoria: "fonte",
    fabricante: "gigabyte",
    id: uuidv4(),
    img: "/images/fonte-gigabyte-p550b.jpg",
    garantia: "36 meses",
    name: "Fonte Gigabyte GP-P550B 550W, 80 Plus Bronze - 28200-P550B-1BRR",
    pathName: "fonte-gigabyte-gpp550b-550w-80-plus-bronze-28200p550b1brr",
    pPrazo: 505,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Marca: Gigabyte",
      "Modelo: 28200-P450B-1BRR",
      "PFC: PFC ativo (> 0,9 típico)",
      "Tensão de entrada: 100-240 Vac (gama completa)",
      "Corrente de entrada: 8-4 A",
      "Frequência de entrada: 60-50 Hz",
      "Capacidade de saída: 450W",
      "80 PLUS: Bronze",
      "Eficiência: 85% em carga típica",
      "Dimensões: 150 x 140 x 86 mm",
      "Peso: 1912 gramas (bruto com embalagem)",
    ],
  },
  {
    categoria: "fonte",
    fabricante: "xpg",
    id: uuidv4(),
    img: "/images/fonte-xpg-750.jpg",
    garantia: "36 meses",
    name: "Fonte XPG Core Reactor, 750W, 80 Plus Gold Modular",
    pathName: "fonte-xpg-core-reactor-750w-80-plus-gold-modular",
    pPrazo: 940,
    tags: [],
    destaque: false,
    promo: false,
    specs: [
      "Marca: Gigabyte",
      "Modelo: 28200-P450B-1BRR",
      "PFC: PFC ativo (> 0,9 típico)",
      "Tensão de entrada: 100-240 Vac (gama completa)",
      "Corrente de entrada: 8-4 A",
      "Frequência de entrada: 60-50 Hz",
      "Capacidade de saída: 450W",
      "80 PLUS: Bronze",
      "Eficiência: 85% em carga típica",
      "Dimensões: 150 x 140 x 86 mm",
      "Peso: 1912 gramas (bruto com embalagem)",
    ],
  },
  {
    categoria: "fonte",
    fabricante: "blue case",
    id: uuidv4(),
    img: "/images/fonte-xpg-650.jpg",
    garantia: "36 meses",
    name: "Fonte XPG Pylon, 650W, 80 Plus Bronze - PYLON650B-BKCBR",
    pathName: "fonte-xpg-pylon-650w-80-plus-bronze-pylon650bbkcbr",
    pPrazo: 590,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Marca: Gigabyte",
      "Modelo: 28200-P450B-1BRR",
      "PFC: PFC ativo (> 0,9 típico)",
      "Tensão de entrada: 100-240 Vac (gama completa)",
      "Corrente de entrada: 8-4 A",
      "Frequência de entrada: 60-50 Hz",
      "Capacidade de saída: 450W",
      "80 PLUS: Bronze",
      "Eficiência: 85% em carga típica",
      "Dimensões: 150 x 140 x 86 mm",
      "Peso: 1912 gramas (bruto com embalagem)",
    ],
  },
  {
    categoria: "placa-de-video",
    fabricante: "zotac",
    id: uuidv4(),
    img: "/images/gpu-rtx-2060.jpg",
    garantia: "24 meses",
    name: "Placa de Vídeo Zotac Gaming NVIDIA GeForce RTX 2060, 6GB, GDDR6 - ZT-T20600H-10M",
    pathName:
      "placa-de-vídeo-zotac-gaming-nvidia-geforce-rtx-2060-6gb-gddr6-ztt20600h10m",
    pPrazo: 4000,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Marca: Zotac",
      "Modelo: ZT-T20600H-10M",
      "Núcleos CUDA: 1920",
      "Clock Boost  1680 MHz",
      "Capacidade: 6GB GDDR5",
      "Barramento: 192 bits",
      "PCI Express 3.0",
      "Resfriamento: Ventilador duplo",
      "Dimensões: 209.6 x 119.3 x 41mm",
      "Fonte de Alimentação Recomendada: 500W",
      "Consumo de Energia: 160W",
      "Entrada de Energia: 8 pinos",
    ],
  },
  {
    categoria: "placa-de-video",
    fabricante: "zotac",
    id: uuidv4(),
    img: "/images/gpu-rtx-3050.jpg",
    garantia: "24 meses",
    name: "Placa de Vídeo Zotac Gaming NVIDIA Geforce RTX 3050 Twin Edge, 8GB, GDDR6, LHR, Ray Tracing, VR Ready - ZT-A30500E-10M",
    pathName:
      "placa-de-vídeo-zotac-gaming-nvidia-geforce-rtx-3050-twin-edge-8gb-gddr6-lhr-ray-tracing-vr-ready-zta30500e10m",
    pPrazo: 3500,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Marca: Zotac",
      "Modelo: ZT-T20600H-10M",
      "Núcleos CUDA: 1920",
      "Clock Boost  1680 MHz",
      "Capacidade: 6GB GDDR5",
      "Barramento: 192 bits",
      "PCI Express 3.0",
      "Resfriamento: Ventilador duplo",
      "Dimensões: 209.6 x 119.3 x 41mm",
      "Fonte de Alimentação Recomendada: 500W",
      "Consumo de Energia: 160W",
      "Entrada de Energia: 8 pinos",
    ],
  },
  {
    categoria: "placa-de-video",
    fabricante: "pc yes",
    id: uuidv4(),
    img: "/images/gpu-rx-550.jpg",
    garantia: "24 meses",
    name: "Placa de Vídeo Pcyes AMD Radeon RX 550, 4GB, GDDR5, Grafiti Series - PAJRX550DR5DF",
    pathName:
      "placa-de-vídeo-pcyes-amd-radeon-rx-550-4gb-gddr5-grafiti-series-pajrx550dr5df",
    pPrazo: 1100,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Marca: Zotac",
      "Modelo: ZT-T20600H-10M",
      "Núcleos CUDA: 1920",
      "Clock Boost  1680 MHz",
      "Capacidade: 6GB GDDR5",
      "Barramento: 192 bits",
      "PCI Express 3.0",
      "Resfriamento: Ventilador duplo",
      "Dimensões: 209.6 x 119.3 x 41mm",
      "Fonte de Alimentação Recomendada: 500W",
      "Consumo de Energia: 160W",
      "Entrada de Energia: 8 pinos",
    ],
  },
  {
    categoria: "placa-de-video",
    fabricante: "zotac",
    id: uuidv4(),
    img: "/images/gpu-rtx-3060ti.jpg",
    garantia: "24 meses",
    name: "Placa de Vídeo Zotac NVIDIA GeForce RTX 3060 Ti Twin Edge LHR, 8GB, 14.0 Gbps, GDDR6, DLSS, Ray Tracing - ZT-A30610E-10MLHR",
    pathName:
      "placa-de-vídeo-zotac-nvidia-geforce-rtx-3060-ti-twin-edge-lhr-8gb-140-gbps-gddr6-dlss-ray-tracing-zta30610e10mlhr",
    pPrazo: 6000,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Marca: Zotac",
      "Modelo: ZT-T20600H-10M",
      "Núcleos CUDA: 1920",
      "Clock Boost  1680 MHz",
      "Capacidade: 6GB GDDR5",
      "Barramento: 192 bits",
      "PCI Express 3.0",
      "Resfriamento: Ventilador duplo",
      "Dimensões: 209.6 x 119.3 x 41mm",
      "Fonte de Alimentação Recomendada: 500W",
      "Consumo de Energia: 160W",
      "Entrada de Energia: 8 pinos",
    ],
  },
  {
    categoria: "placa-de-video",
    fabricante: "sapphire",
    id: uuidv4(),
    img: "/images/gpu-rx-6500xt.jpg",
    garantia: "24 meses",
    name: "Placa de Vídeo Sapphire Pulse RX 6500 XT Gaming OC, 4GB, GDDR6, AMD - 11314-01-20G",
    pathName:
      "placa-de-vídeo-sapphire-pulse-rx-6500-xt-gaming-oc-4gb-gddr6-amd-113140120g",
    pPrazo: 2000,
    tags: [],
    destaque: false,
    promo: true,
    specs: [
      "Marca: Zotac",
      "Modelo: ZT-T20600H-10M",
      "Núcleos CUDA: 1920",
      "Clock Boost  1680 MHz",
      "Capacidade: 6GB GDDR5",
      "Barramento: 192 bits",
      "PCI Express 3.0",
      "Resfriamento: Ventilador duplo",
      "Dimensões: 209.6 x 119.3 x 41mm",
      "Fonte de Alimentação Recomendada: 500W",
      "Consumo de Energia: 160W",
      "Entrada de Energia: 8 pinos",
    ],
  },
  {
    categoria: "placa-de-video",
    fabricante: "sapphire",
    id: uuidv4(),
    img: "/images/gpu-rx-6600xt.jpg",
    garantia: "24 meses",
    name: "Placa de Vídeo Sapphire PULSE RX6600XT OC, 8GB GDDR6, AMD RDNA 2 Architecture - 11309-03-20G",
    pathName:
      "placa-de-vídeo-sapphire-pulse-rx6600xt-oc-8gb-gddr6-amd-rdna-2-architecture-113090320g",
    pPrazo: 4500,
    tags: [],
    destaque: true,
    promo: false,
    specs: [
      "Marca: Zotac",
      "Modelo: ZT-T20600H-10M",
      "Núcleos CUDA: 1920",
      "Clock Boost  1680 MHz",
      "Capacidade: 6GB GDDR5",
      "Barramento: 192 bits",
      "PCI Express 3.0",
      "Resfriamento: Ventilador duplo",
      "Dimensões: 209.6 x 119.3 x 41mm",
      "Fonte de Alimentação Recomendada: 500W",
      "Consumo de Energia: 160W",
      "Entrada de Energia: 8 pinos",
    ],
  },
];

export default listaItens;
